### ISSUE TITLE
Publish to hackage

### ISSUE THREAD

**Issue by fgaz** [schell/gelatin#16]
@schell do you intend to publish gelatin to hackage?
If yes: what do we need before doing it?

* [x] Add version bounds
* [x] Mark as experimental
* [x] Bump to 0.1.0.0
* [ ] Write minimal documentation and release to hackage
* * [x] gelatin 
* * * [x] gelatin-shaders
* * * * [x] gelatin-gl
* * * * * [x] gelatin-sdl2
* * * * * [x] gelatin-freetype2
* * * * * [ ] gelatin-example
* * * * [ ] gelatin-webgl
* * * [x] gelatin-fruity

**Comment by schell** [comment]
I do plan on it, and thanks for lighting the fire under my seat. I'm fairly certain there are some superfluous modules, so I'll go through and prune them out before release.

**Comment by schell** [comment]
CI builds!

**Comment by schell** [comment]
Okay - I think we're done. I'm not sure it's necessary to upload gelatin-example and I'm not ready to support gelatin-webgl officially. What do you think, @fgaz?

**Comment by fgaz** [comment]
Nice!
While there are some *-example packages on hackage I too think it's not necessary to upload gelatin-example (not right now at least). I also agree on webgl.

Just be sure to upload them in dependency order (ie. upload something only when you already uploaded all its deps), so that the matrix will give some results on the first try (and faster too).

**Comment by schell** [comment]
It's all done now and hackage is done building docs. Thanks for your help! Next release will focus on documentation and cleanup.

**Comment by fgaz** [comment]
Oops yeah, I noticed you already uploaded them just after posting that comment
